steps:
    - id: "docker build"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "us.gcr.io/$PROJECT_ID/firestore-fastapi", "--file", "docker/Dockerfile", "."]

    - id: "docker test"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "us.gcr.io/$PROJECT_ID/firestore-fastapi-test", "--file", "docker/test/Dockerfile", "."]

    - id: "docker push"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "us.gcr.io/$PROJECT_ID/firestore-fastapi"]

    - id: "cloud run deploy"
      name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      args:
          - sh
          - -c
          - |
            gcloud run deploy \
            firestore-fastapi-$BRANCH_NAME \
            --image=us.gcr.io/$PROJECT_ID/firestore-fastapi:latest \
            --cpu=2 \
            --port=8080 \
            --memory=2048Mi \
            --timeout=600 \
            --concurrency=20 \
            --platform=managed \
            --max-instances=1000 \
            --region=us-central1 \
            --allow-unauthenticated \
            --revision-suffix=$SHORT_SHA \
            --set-env-vars=PROJECT_ID=$PROJECT_ID,SHORT_SHA=$SHORT_SHA
