steps:
    - id: "docker build"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "us.gcr.io/$PROJECT_ID/api", "."]

    - id: "docker test"
      name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "us.gcr.io/$PROJECT_ID/api-test", "--file", "Dockerfile-test", "."]

    - id: "docker push"
      name: "gcr.io/cloud-builders/docker"
      args: ["push", "us.gcr.io/$PROJECT_ID/api"]

    - id: "cloud run deploy"
      name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      args:
          - sh
          - -c
          - |
            gcloud run deploy \
            api-$BRANCH_NAME \
            --image=us.gcr.io/$PROJECT_ID/api:latest \
            --cpu=2 \
            --port=8080 \
            --memory=2048Mi \
            --timeout=600 \
            --concurrency=20 \
            --platform=managed \
            --max-instances=1000 \
            --region=us-central1 \
            --allow-unauthenticated \
            --revision-suffix=$SHORT_SHA \
            --set-env-vars=PROJECT_ID=$PROJECT_ID,SHORT_SHA=$SHORT_SHA \
            --set-cloudsql-instances=$PROJECT_ID:us-central1:delta-api \
            --service-account=deltabot@$PROJECT_ID.iam.gserviceaccount.com
